version: "3"

networks:
  gin:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3004:8080"
    depends_on:
      - postgres
    networks:
      - gin
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5430:5432"
    
    environment:
      POSTGRES_DB: gin
      POSTGRES_USER: gin
      POSTGRES_PASSWORD: gin
    networks:
      - gin
